// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package test

var TestFields = struct {
	StringField          string
	NumberField          string
	BoolField            string
	EnumField            string
	MessageField         string
	RepeatedStringField  string
	RepeatedMessageField string
	NumberValueField     string
	StringValueField     string
	BoolValueField       string
	TimeValueField       string
	DurationValueField   string
	OptionalStringField  string
	OptionalNumberField  string
	OptionalBoolField    string
	OptionalEnumField    string
	OneofStringField     string
	OneofNumberField     string
	OneofMessageField    string
}{
	StringField:          "string_field",
	NumberField:          "number_field",
	BoolField:            "bool_field",
	EnumField:            "enum_field",
	MessageField:         "message_field",
	RepeatedStringField:  "repeated_string_field",
	RepeatedMessageField: "repeated_message_field",
	NumberValueField:     "number_value_field",
	StringValueField:     "string_value_field",
	BoolValueField:       "bool_value_field",
	TimeValueField:       "time_value_field",
	DurationValueField:   "duration_value_field",
	OptionalStringField:  "optional_string_field",
	OptionalNumberField:  "optional_number_field",
	OptionalBoolField:    "optional_bool_field",
	OptionalEnumField:    "optional_enum_field",
	OneofStringField:     "oneof_string_field",
	OneofNumberField:     "oneof_number_field",
	OneofMessageField:    "oneof_message_field",
}
