// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: filters/field_filter.proto

package filters

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Condition *FieldFilter  `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	AndExprs  []*Expression `protobuf:"bytes,2,rep,name=and_exprs,json=andExprs,proto3" json:"and_exprs,omitempty"`
	OrExprs   []*Expression `protobuf:"bytes,3,rep,name=or_exprs,json=orExprs,proto3" json:"or_exprs,omitempty"`
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{0}
}

func (x *Expression) GetCondition() *FieldFilter {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *Expression) GetAndExprs() []*Expression {
	if x != nil {
		return x.AndExprs
	}
	return nil
}

func (x *Expression) GetOrExprs() []*Expression {
	if x != nil {
		return x.OrExprs
	}
	return nil
}

type FieldsFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Filters is a map of <field path, Filter>
	Filters map[string]*Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FieldsFilter) Reset() {
	*x = FieldsFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsFilter) ProtoMessage() {}

func (x *FieldsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsFilter.ProtoReflect.Descriptor instead.
func (*FieldsFilter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FieldsFilter) GetFilters() map[string]*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type FieldFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Field is the field's path
	Field  string  `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Filter *Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *FieldFilter) Reset() {
	*x = FieldFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldFilter) ProtoMessage() {}

func (x *FieldFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldFilter.ProtoReflect.Descriptor instead.
func (*FieldFilter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{2}
}

func (x *FieldFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldFilter) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Match:
	//	*Filter_String_
	//	*Filter_Number
	//	*Filter_Bool
	//	*Filter_Null
	//	*Filter_Time
	//	*Filter_Duration
	Match isFilter_Match `protobuf_oneof:"match"`
	// Not negates the match result
	Not bool `protobuf:"varint,7,opt,name=not,proto3" json:"not,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{3}
}

func (m *Filter) GetMatch() isFilter_Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (x *Filter) GetString_() *StringFilter {
	if x, ok := x.GetMatch().(*Filter_String_); ok {
		return x.String_
	}
	return nil
}

func (x *Filter) GetNumber() *NumberFilter {
	if x, ok := x.GetMatch().(*Filter_Number); ok {
		return x.Number
	}
	return nil
}

func (x *Filter) GetBool() *BoolFilter {
	if x, ok := x.GetMatch().(*Filter_Bool); ok {
		return x.Bool
	}
	return nil
}

func (x *Filter) GetNull() *NullFilter {
	if x, ok := x.GetMatch().(*Filter_Null); ok {
		return x.Null
	}
	return nil
}

func (x *Filter) GetTime() *TimeFilter {
	if x, ok := x.GetMatch().(*Filter_Time); ok {
		return x.Time
	}
	return nil
}

func (x *Filter) GetDuration() *DurationFilter {
	if x, ok := x.GetMatch().(*Filter_Duration); ok {
		return x.Duration
	}
	return nil
}

func (x *Filter) GetNot() bool {
	if x != nil {
		return x.Not
	}
	return false
}

type isFilter_Match interface {
	isFilter_Match()
}

type Filter_String_ struct {
	String_ *StringFilter `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Filter_Number struct {
	Number *NumberFilter `protobuf:"bytes,2,opt,name=number,proto3,oneof"`
}

type Filter_Bool struct {
	Bool *BoolFilter `protobuf:"bytes,3,opt,name=bool,proto3,oneof"`
}

type Filter_Null struct {
	Null *NullFilter `protobuf:"bytes,4,opt,name=null,proto3,oneof"`
}

type Filter_Time struct {
	Time *TimeFilter `protobuf:"bytes,5,opt,name=time,proto3,oneof"`
}

type Filter_Duration struct {
	Duration *DurationFilter `protobuf:"bytes,6,opt,name=duration,proto3,oneof"`
}

func (*Filter_String_) isFilter_Match() {}

func (*Filter_Number) isFilter_Match() {}

func (*Filter_Bool) isFilter_Match() {}

func (*Filter_Null) isFilter_Match() {}

func (*Filter_Time) isFilter_Match() {}

func (*Filter_Duration) isFilter_Match() {}

type StringFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Condition:
	//	*StringFilter_Equals
	//	*StringFilter_Regex
	//	*StringFilter_In_
	Condition       isStringFilter_Condition `protobuf_oneof:"condition"`
	CaseInsensitive bool                     `protobuf:"varint,4,opt,name=case_insensitive,json=caseInsensitive,proto3" json:"case_insensitive,omitempty"`
}

func (x *StringFilter) Reset() {
	*x = StringFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringFilter) ProtoMessage() {}

func (x *StringFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringFilter.ProtoReflect.Descriptor instead.
func (*StringFilter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{4}
}

func (m *StringFilter) GetCondition() isStringFilter_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (x *StringFilter) GetEquals() string {
	if x, ok := x.GetCondition().(*StringFilter_Equals); ok {
		return x.Equals
	}
	return ""
}

func (x *StringFilter) GetRegex() string {
	if x, ok := x.GetCondition().(*StringFilter_Regex); ok {
		return x.Regex
	}
	return ""
}

func (x *StringFilter) GetIn() *StringFilter_In {
	if x, ok := x.GetCondition().(*StringFilter_In_); ok {
		return x.In
	}
	return nil
}

func (x *StringFilter) GetCaseInsensitive() bool {
	if x != nil {
		return x.CaseInsensitive
	}
	return false
}

type isStringFilter_Condition interface {
	isStringFilter_Condition()
}

type StringFilter_Equals struct {
	Equals string `protobuf:"bytes,1,opt,name=equals,proto3,oneof"`
}

type StringFilter_Regex struct {
	Regex string `protobuf:"bytes,2,opt,name=regex,proto3,oneof"`
}

type StringFilter_In_ struct {
	In *StringFilter_In `protobuf:"bytes,3,opt,name=in,proto3,oneof"`
}

func (*StringFilter_Equals) isStringFilter_Condition() {}

func (*StringFilter_Regex) isStringFilter_Condition() {}

func (*StringFilter_In_) isStringFilter_Condition() {}

type NumberFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Condition:
	//	*NumberFilter_Equals
	//	*NumberFilter_Sup
	//	*NumberFilter_Inf
	//	*NumberFilter_In_
	Condition isNumberFilter_Condition `protobuf_oneof:"condition"`
}

func (x *NumberFilter) Reset() {
	*x = NumberFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberFilter) ProtoMessage() {}

func (x *NumberFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberFilter.ProtoReflect.Descriptor instead.
func (*NumberFilter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{5}
}

func (m *NumberFilter) GetCondition() isNumberFilter_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (x *NumberFilter) GetEquals() float64 {
	if x, ok := x.GetCondition().(*NumberFilter_Equals); ok {
		return x.Equals
	}
	return 0
}

func (x *NumberFilter) GetSup() float64 {
	if x, ok := x.GetCondition().(*NumberFilter_Sup); ok {
		return x.Sup
	}
	return 0
}

func (x *NumberFilter) GetInf() float64 {
	if x, ok := x.GetCondition().(*NumberFilter_Inf); ok {
		return x.Inf
	}
	return 0
}

func (x *NumberFilter) GetIn() *NumberFilter_In {
	if x, ok := x.GetCondition().(*NumberFilter_In_); ok {
		return x.In
	}
	return nil
}

type isNumberFilter_Condition interface {
	isNumberFilter_Condition()
}

type NumberFilter_Equals struct {
	Equals float64 `protobuf:"fixed64,1,opt,name=equals,proto3,oneof"`
}

type NumberFilter_Sup struct {
	Sup float64 `protobuf:"fixed64,2,opt,name=sup,proto3,oneof"`
}

type NumberFilter_Inf struct {
	Inf float64 `protobuf:"fixed64,3,opt,name=inf,proto3,oneof"`
}

type NumberFilter_In_ struct {
	In *NumberFilter_In `protobuf:"bytes,4,opt,name=in,proto3,oneof"`
}

func (*NumberFilter_Equals) isNumberFilter_Condition() {}

func (*NumberFilter_Sup) isNumberFilter_Condition() {}

func (*NumberFilter_Inf) isNumberFilter_Condition() {}

func (*NumberFilter_In_) isNumberFilter_Condition() {}

type NullFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullFilter) Reset() {
	*x = NullFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullFilter) ProtoMessage() {}

func (x *NullFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullFilter.ProtoReflect.Descriptor instead.
func (*NullFilter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{6}
}

type BoolFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equals bool `protobuf:"varint,1,opt,name=equals,proto3" json:"equals,omitempty"`
}

func (x *BoolFilter) Reset() {
	*x = BoolFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolFilter) ProtoMessage() {}

func (x *BoolFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolFilter.ProtoReflect.Descriptor instead.
func (*BoolFilter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{7}
}

func (x *BoolFilter) GetEquals() bool {
	if x != nil {
		return x.Equals
	}
	return false
}

type TimeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Condition:
	//	*TimeFilter_Equals
	//	*TimeFilter_Before
	//	*TimeFilter_After
	Condition isTimeFilter_Condition `protobuf_oneof:"condition"`
}

func (x *TimeFilter) Reset() {
	*x = TimeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeFilter) ProtoMessage() {}

func (x *TimeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeFilter.ProtoReflect.Descriptor instead.
func (*TimeFilter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{8}
}

func (m *TimeFilter) GetCondition() isTimeFilter_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (x *TimeFilter) GetEquals() *timestamppb.Timestamp {
	if x, ok := x.GetCondition().(*TimeFilter_Equals); ok {
		return x.Equals
	}
	return nil
}

func (x *TimeFilter) GetBefore() *timestamppb.Timestamp {
	if x, ok := x.GetCondition().(*TimeFilter_Before); ok {
		return x.Before
	}
	return nil
}

func (x *TimeFilter) GetAfter() *timestamppb.Timestamp {
	if x, ok := x.GetCondition().(*TimeFilter_After); ok {
		return x.After
	}
	return nil
}

type isTimeFilter_Condition interface {
	isTimeFilter_Condition()
}

type TimeFilter_Equals struct {
	Equals *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=equals,proto3,oneof"`
}

type TimeFilter_Before struct {
	Before *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=before,proto3,oneof"`
}

type TimeFilter_After struct {
	After *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=after,proto3,oneof"`
}

func (*TimeFilter_Equals) isTimeFilter_Condition() {}

func (*TimeFilter_Before) isTimeFilter_Condition() {}

func (*TimeFilter_After) isTimeFilter_Condition() {}

type DurationFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Condition:
	//	*DurationFilter_Equals
	//	*DurationFilter_Sup
	//	*DurationFilter_Inf
	Condition isDurationFilter_Condition `protobuf_oneof:"condition"`
}

func (x *DurationFilter) Reset() {
	*x = DurationFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DurationFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationFilter) ProtoMessage() {}

func (x *DurationFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationFilter.ProtoReflect.Descriptor instead.
func (*DurationFilter) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{9}
}

func (m *DurationFilter) GetCondition() isDurationFilter_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (x *DurationFilter) GetEquals() *durationpb.Duration {
	if x, ok := x.GetCondition().(*DurationFilter_Equals); ok {
		return x.Equals
	}
	return nil
}

func (x *DurationFilter) GetSup() *durationpb.Duration {
	if x, ok := x.GetCondition().(*DurationFilter_Sup); ok {
		return x.Sup
	}
	return nil
}

func (x *DurationFilter) GetInf() *durationpb.Duration {
	if x, ok := x.GetCondition().(*DurationFilter_Inf); ok {
		return x.Inf
	}
	return nil
}

type isDurationFilter_Condition interface {
	isDurationFilter_Condition()
}

type DurationFilter_Equals struct {
	Equals *durationpb.Duration `protobuf:"bytes,1,opt,name=equals,proto3,oneof"`
}

type DurationFilter_Sup struct {
	Sup *durationpb.Duration `protobuf:"bytes,2,opt,name=sup,proto3,oneof"`
}

type DurationFilter_Inf struct {
	Inf *durationpb.Duration `protobuf:"bytes,3,opt,name=inf,proto3,oneof"`
}

func (*DurationFilter_Equals) isDurationFilter_Condition() {}

func (*DurationFilter_Sup) isDurationFilter_Condition() {}

func (*DurationFilter_Inf) isDurationFilter_Condition() {}

type StringFilter_In struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *StringFilter_In) Reset() {
	*x = StringFilter_In{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringFilter_In) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringFilter_In) ProtoMessage() {}

func (x *StringFilter_In) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringFilter_In.ProtoReflect.Descriptor instead.
func (*StringFilter_In) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{4, 0}
}

func (x *StringFilter_In) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type NumberFilter_In struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *NumberFilter_In) Reset() {
	*x = NumberFilter_In{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_field_filter_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberFilter_In) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberFilter_In) ProtoMessage() {}

func (x *NumberFilter_In) ProtoReflect() protoreflect.Message {
	mi := &file_filters_field_filter_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberFilter_In.ProtoReflect.Descriptor instead.
func (*NumberFilter_In) Descriptor() ([]byte, []int) {
	return file_filters_field_filter_proto_rawDescGZIP(), []int{5, 0}
}

func (x *NumberFilter_In) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_filters_field_filter_proto protoreflect.FileDescriptor

var file_filters_field_filter_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6c, 0x69,
	0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x09, 0x61,
	0x6e, 0x64, 0x5f, 0x65, 0x78, 0x70, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x72, 0x73, 0x12, 0x3f,
	0x0a, 0x08, 0x6f, 0x72, 0x5f, 0x65, 0x78, 0x70, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x72, 0x45, 0x78, 0x70, 0x72, 0x73, 0x22,
	0xbb, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x4d, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x33, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x1a,
	0x5c, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x36, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5d, 0x0a,
	0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x38, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xa3, 0x03, 0x0a,
	0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x04, 0x62,
	0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x3a, 0x0a, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x6e,
	0x75, 0x6c, 0x6c, 0x12, 0x3a, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x46, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x6e, 0x6f, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x22, 0xd3, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a,
	0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x72, 0x65, 0x67, 0x65, 0x78, 0x12, 0x3b, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x48, 0x00, 0x52, 0x02,
	0x69, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x65, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x63, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x1a, 0x1c, 0x0a,
	0x02, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb8, 0x01, 0x0a, 0x0c, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x06, 0x65, 0x71, 0x75,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x65, 0x71, 0x75,
	0x61, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x00, 0x52, 0x03, 0x73, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x66, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x66, 0x12, 0x3b, 0x0a, 0x02, 0x69,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e,
	0x49, 0x6e, 0x48, 0x00, 0x52, 0x02, 0x69, 0x6e, 0x1a, 0x1c, 0x0a, 0x02, 0x49, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x0c, 0x0a, 0x0a, 0x4e, 0x75, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x22, 0x24, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x48, 0x00, 0x52, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x34, 0x0a, 0x06,
	0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x06, 0x62, 0x65, 0x66, 0x6f,
	0x72, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52,
	0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xb0, 0x01, 0x0a, 0x0e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x2d, 0x0a, 0x03, 0x73,
	0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x73, 0x75, 0x70, 0x12, 0x2d, 0x0a, 0x03, 0x69, 0x6e,
	0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x66, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x7b, 0x0a, 0x18, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x42, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x50, 0x01, 0x5a, 0x2b, 0x67, 0x6f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x3b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0xf8,
	0x01, 0x01, 0xa2, 0x02, 0x04, 0x4c, 0x4b, 0x50, 0x46, 0xaa, 0x02, 0x17, 0x4c, 0x69, 0x6e, 0x6b,
	0x61, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filters_field_filter_proto_rawDescOnce sync.Once
	file_filters_field_filter_proto_rawDescData = file_filters_field_filter_proto_rawDesc
)

func file_filters_field_filter_proto_rawDescGZIP() []byte {
	file_filters_field_filter_proto_rawDescOnce.Do(func() {
		file_filters_field_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_filters_field_filter_proto_rawDescData)
	})
	return file_filters_field_filter_proto_rawDescData
}

var file_filters_field_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_filters_field_filter_proto_goTypes = []interface{}{
	(*Expression)(nil),            // 0: linka.cloud.protofilters.Expression
	(*FieldsFilter)(nil),          // 1: linka.cloud.protofilters.FieldsFilter
	(*FieldFilter)(nil),           // 2: linka.cloud.protofilters.FieldFilter
	(*Filter)(nil),                // 3: linka.cloud.protofilters.Filter
	(*StringFilter)(nil),          // 4: linka.cloud.protofilters.StringFilter
	(*NumberFilter)(nil),          // 5: linka.cloud.protofilters.NumberFilter
	(*NullFilter)(nil),            // 6: linka.cloud.protofilters.NullFilter
	(*BoolFilter)(nil),            // 7: linka.cloud.protofilters.BoolFilter
	(*TimeFilter)(nil),            // 8: linka.cloud.protofilters.TimeFilter
	(*DurationFilter)(nil),        // 9: linka.cloud.protofilters.DurationFilter
	nil,                           // 10: linka.cloud.protofilters.FieldsFilter.FiltersEntry
	(*StringFilter_In)(nil),       // 11: linka.cloud.protofilters.StringFilter.In
	(*NumberFilter_In)(nil),       // 12: linka.cloud.protofilters.NumberFilter.In
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
}
var file_filters_field_filter_proto_depIdxs = []int32{
	2,  // 0: linka.cloud.protofilters.Expression.condition:type_name -> linka.cloud.protofilters.FieldFilter
	0,  // 1: linka.cloud.protofilters.Expression.and_exprs:type_name -> linka.cloud.protofilters.Expression
	0,  // 2: linka.cloud.protofilters.Expression.or_exprs:type_name -> linka.cloud.protofilters.Expression
	10, // 3: linka.cloud.protofilters.FieldsFilter.filters:type_name -> linka.cloud.protofilters.FieldsFilter.FiltersEntry
	3,  // 4: linka.cloud.protofilters.FieldFilter.filter:type_name -> linka.cloud.protofilters.Filter
	4,  // 5: linka.cloud.protofilters.Filter.string:type_name -> linka.cloud.protofilters.StringFilter
	5,  // 6: linka.cloud.protofilters.Filter.number:type_name -> linka.cloud.protofilters.NumberFilter
	7,  // 7: linka.cloud.protofilters.Filter.bool:type_name -> linka.cloud.protofilters.BoolFilter
	6,  // 8: linka.cloud.protofilters.Filter.null:type_name -> linka.cloud.protofilters.NullFilter
	8,  // 9: linka.cloud.protofilters.Filter.time:type_name -> linka.cloud.protofilters.TimeFilter
	9,  // 10: linka.cloud.protofilters.Filter.duration:type_name -> linka.cloud.protofilters.DurationFilter
	11, // 11: linka.cloud.protofilters.StringFilter.in:type_name -> linka.cloud.protofilters.StringFilter.In
	12, // 12: linka.cloud.protofilters.NumberFilter.in:type_name -> linka.cloud.protofilters.NumberFilter.In
	13, // 13: linka.cloud.protofilters.TimeFilter.equals:type_name -> google.protobuf.Timestamp
	13, // 14: linka.cloud.protofilters.TimeFilter.before:type_name -> google.protobuf.Timestamp
	13, // 15: linka.cloud.protofilters.TimeFilter.after:type_name -> google.protobuf.Timestamp
	14, // 16: linka.cloud.protofilters.DurationFilter.equals:type_name -> google.protobuf.Duration
	14, // 17: linka.cloud.protofilters.DurationFilter.sup:type_name -> google.protobuf.Duration
	14, // 18: linka.cloud.protofilters.DurationFilter.inf:type_name -> google.protobuf.Duration
	3,  // 19: linka.cloud.protofilters.FieldsFilter.FiltersEntry.value:type_name -> linka.cloud.protofilters.Filter
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_filters_field_filter_proto_init() }
func file_filters_field_filter_proto_init() {
	if File_filters_field_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filters_field_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldsFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DurationFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringFilter_In); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_field_filter_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberFilter_In); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_filters_field_filter_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Filter_String_)(nil),
		(*Filter_Number)(nil),
		(*Filter_Bool)(nil),
		(*Filter_Null)(nil),
		(*Filter_Time)(nil),
		(*Filter_Duration)(nil),
	}
	file_filters_field_filter_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*StringFilter_Equals)(nil),
		(*StringFilter_Regex)(nil),
		(*StringFilter_In_)(nil),
	}
	file_filters_field_filter_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*NumberFilter_Equals)(nil),
		(*NumberFilter_Sup)(nil),
		(*NumberFilter_Inf)(nil),
		(*NumberFilter_In_)(nil),
	}
	file_filters_field_filter_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*TimeFilter_Equals)(nil),
		(*TimeFilter_Before)(nil),
		(*TimeFilter_After)(nil),
	}
	file_filters_field_filter_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*DurationFilter_Equals)(nil),
		(*DurationFilter_Sup)(nil),
		(*DurationFilter_Inf)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filters_field_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filters_field_filter_proto_goTypes,
		DependencyIndexes: file_filters_field_filter_proto_depIdxs,
		MessageInfos:      file_filters_field_filter_proto_msgTypes,
	}.Build()
	File_filters_field_filter_proto = out.File
	file_filters_field_filter_proto_rawDesc = nil
	file_filters_field_filter_proto_goTypes = nil
	file_filters_field_filter_proto_depIdxs = nil
}
