// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package filters

var ExpressionFields = struct {
	Condition string
	AndExprs  string
	OrExprs   string
}{
	Condition: "condition",
	AndExprs:  "and_exprs",
	OrExprs:   "or_exprs",
}

var FieldsFilterFields = struct {
	Filters string
}{
	Filters: "filters",
}

var FieldFilterFields = struct {
	Field  string
	Filter string
}{
	Field:  "field",
	Filter: "filter",
}

var FilterFields = struct {
	String_  string
	Number   string
	Bool     string
	Null     string
	Time     string
	Duration string
	Not      string
}{
	String_:  "string",
	Number:   "number",
	Bool:     "bool",
	Null:     "null",
	Time:     "time",
	Duration: "duration",
	Not:      "not",
}

var StringFilterFields = struct {
	Equals          string
	Regex           string
	HasPrefix       string
	HasSuffix       string
	In              string
	Sup             string
	Inf             string
	CaseInsensitive string
}{
	Equals:          "equals",
	Regex:           "regex",
	HasPrefix:       "has_prefix",
	HasSuffix:       "has_suffix",
	In:              "in",
	Sup:             "sup",
	Inf:             "inf",
	CaseInsensitive: "case_insensitive",
}

var NumberFilterFields = struct {
	Equals string
	Sup    string
	Inf    string
	In     string
}{
	Equals: "equals",
	Sup:    "sup",
	Inf:    "inf",
	In:     "in",
}

var NullFilterFields = struct {
}{}

var BoolFilterFields = struct {
	Equals string
}{
	Equals: "equals",
}

var TimeFilterFields = struct {
	Equals string
	Before string
	After  string
}{
	Equals: "equals",
	Before: "before",
	After:  "after",
}

var DurationFilterFields = struct {
	Equals string
	Sup    string
	Inf    string
}{
	Equals: "equals",
	Sup:    "sup",
	Inf:    "inf",
}

var StringFilter_InFields = struct {
	Values string
}{
	Values: "values",
}

var NumberFilter_InFields = struct {
	Values string
}{
	Values: "values",
}
